<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" alt="CLRSWY_LOGO" title="Open and Execute in Google Colaboratory"></a><br/>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [ ]:
import numpy as np


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [ ]:
my_list=[5,10,15,20,25]
np.array(my_list)


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [ ]:
np.zeros((5,5))



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [ ]:
arr1 = np.ones((4,4),dtype=int)
arr1


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [ ]:
arr1[:,:] = 7
arr1



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [ ]:
np.full((4,4),7)



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (both inclusive).

In [ ]:
a = np.arange(2,17)
a[a % 2 == 0]



array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 (inclusive) to 25 (exclusive).

In [ ]:
np.arange(25).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 (inclusive) to 25 (exclusive) using linspace method.

In [ ]:
np.linspace(0,24,25,dtype=int).reshape(5,5)
# np.linspace(0,25,25,dtype=int, endpoint=False).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [ ]:
np.random.rand(5)


array([0.83092944, 0.2866751 , 0.36391215, 0.88240797, 0.12400657])

### 11. Generate a 5 by 5 array and fills it with random values as per the standard normal distribution.


In [ ]:
np.random.randn(5,5)



array([[ 1.44366194,  0.29049462,  0.55383168,  1.38031302, -1.33458661],
       [-2.17615199,  1.94039231,  0.87164478, -0.25985031, -0.45442036],
       [ 1.2619348 ,  0.13148221, -0.40293412, -0.07685069, -1.81299192],
       [ 0.55701564,  0.93502124,  1.70223887, -2.63021007, -0.0238561 ],
       [ 1.31899577,  0.63987301, -1.36922178, -0.19530078, -2.13027894]])

### 12. Generate a 3*4 array of random int numbers between 20 and 50 (both inclusive).

In [ ]:
np.random.randint(20,50,size=(3,4))


array([[42, 34, 28, 26],
       [39, 30, 29, 47],
       [38, 20, 39, 39]])

### 13. Generate an array named "ranarr"consisting of randomly 48 numbers (int) and reshape this array 6 by 8 in different ways (remember the power of -1).

In [ ]:
ranarr = np.random.randint(0, 60, 48)
ranarr


array([47,  8, 26,  0, 53,  8,  5, 41,  1, 55, 49, 32, 43,  7, 52, 41,  2,
       18, 43,  1, 51, 48, 44,  9,  4, 10, 33, 52, 54, 42, 22, 38, 52, 28,
       49, 52, 39, 46, 38, 11, 47, 52, 46, 33, 16, 11, 52, 16])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)
ranarr.reshape(6,8)


array([[47,  8, 26,  0, 53,  8,  5, 41],
       [ 1, 55, 49, 32, 43,  7, 52, 41],
       [ 2, 18, 43,  1, 51, 48, 44,  9],
       [ 4, 10, 33, 52, 54, 42, 22, 38],
       [52, 28, 49, 52, 39, 46, 38, 11],
       [47, 52, 46, 33, 16, 11, 52, 16]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
np.reshape(ranarr, (6,-1))


array([[47,  8, 26,  0, 53,  8,  5, 41],
       [ 1, 55, 49, 32, 43,  7, 52, 41],
       [ 2, 18, 43,  1, 51, 48, 44,  9],
       [ 4, 10, 33, 52, 54, 42, 22, 38],
       [52, 28, 49, 52, 39, 46, 38, 11],
       [47, 52, 46, 33, 16, 11, 52, 16]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
np.reshape(ranarr, (6,-1))


array([[47,  8, 26,  0, 53,  8,  5, 41],
       [ 1, 55, 49, 32, 43,  7, 52, 41],
       [ 2, 18, 43,  1, 51, 48, 44,  9],
       [ 4, 10, 33, 52, 54, 42, 22, 38],
       [52, 28, 49, 52, 39, 46, 38, 11],
       [47, 52, 46, 33, 16, 11, 52, 16]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [ ]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [ ]:
a[1:-1,1:-1]


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [ ]:
a[:,0]


array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [ ]:
a[1,::2]


array([5, 7])

### 17. Assign 77 to every cell in 3rd column (index number 2).

In [ ]:
a[:,2] = 77
a


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take the value at the 2nd row (index number 1) and 1st column (index number 0) & (b) the value at the 4th row (index number 3) and 3rd column (index number 2) at the same time.

In [ ]:
a[[1,3],[0,2]]


array([ 5, 77])

### 19. What are the common values present at the intersection of the second (index number 1) and last (index number 3) row with a step size of 2 and the first (index number 0) and last column with a step size of 2 in the given array?

In [ ]:
a[1::2,::2]


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat"

import math
b = a[a<10] + a[a>12]
b

array([78, 79, 81, 18, 20, 85, 25])

In [ ]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat"
a[a<10]




array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat"
a[a>12]



array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat"
b = a[a<10] + a[a>12]
b



array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [ ]:
b.std()


29.700546274093877

### 22. Get the sum of the values at the 2nd column (index number 1) in the original "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat"
a




array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
# LET US GET BACK THE ORIGINAL ARRAY OF "mat" AGAIN
a




array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
a[:,1].sum()

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat"

c = np.arange(1,17).reshape(4,4)
c


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE
c[:, 2].reshape(-1, 1)



array([[ 3],
       [ 7],
       [11],
       [15]])

In [ ]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?
c[2, :]



array([ 9, 10, 11, 12])

In [ ]:
# LET US GET MEDIAN VALUE
np.median(c[2,:])




10.5

In [ ]:
# LET US GET MEAN VALUE
c[2,:].mean()




10.5

In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE

c[2,:].std()



1.118033988749895

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [ ]:
import pandas as pd



### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.

In [ ]:
# LET US READ Salaries.csv
df = pd.read_csv('Salaries.csv')


In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS

df.head()



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE

df.sample()



Id  EmployeeName                    JobTitle   BasePay  OvertimePay  \
84835  84836  Cynthia L Li  Protective Services Worker  95229.05          0.0   

       OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
84835    1400.0  32888.01  96629.05         129517.06  2013    NaN   

              Agency  Status  
84835  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

df.describe()



Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
df.Year.value_counts(dropna=False)


Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: count, dtype: int64

In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

pd.Series([36159, 36766, 37606, 38123], index=[2011, 2012, 2013, 2014], name='count')
data.index.nunique()



4

In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"
data = pd.Series([36159, 36766, 37606, 38123], index=[2011, 2012, 2013, 2014], name='count')
data.index.values


array([2011, 2012, 2013, 2014], dtype=int64)

### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

df['TotalPay'].max()
#df.TotalPay.max()


567595.43

In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

df['TotalPay'].mean()
# df.TotalPay.mean()



74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

69489

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
len(df[df['TotalPay'] > df['TotalPay'].mean()])

69489

### How much does ALBERT PARDINI make money (including extras, benefits, etc)?

In [ ]:
df['TotalPayBenefits'][df['EmployeeName'] == 'ALBERT PARDINI']
df[df.EmployeeName=='ALBERT PARDINI'].TotalPayBenefits



2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [ ]:
min_pay = df.TotalPayBenefits.min()
df[df['TotalPayBenefits'] == min_pay]['EmployeeName']


148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [ ]:
df['JobTitle'].unique()


array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [ ]:
df['JobTitle'].value_counts().tail(3)



JobTitle
COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: count, dtype: int64

### How many people earned more than avg in 2012? (including extras, benefits, etc)

In [ ]:
df['Id'][(df['TotalPayBenefits'] > df['TotalPayBenefits'].mean()) &
         (df['Year'] == 2012)].count()

20366

### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION FOR THIS QUESTION!

df.apply(lambda x: x.str.contains('Manager', case=False)
             if x.name in ['JobTitle'] else x)['JobTitle'].sum()



4110

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
sal_new = df.iloc[:, [0,1,2,7,8]]
sal_new



Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
sal_new = df.loc[:, ['EmployeeName', 'JobTitle', 'TotalPay', 'TotalPayBenefits']]
sal_new



EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
df['EmployeeName'][(df['TotalPayBenefits'] > df['TotalPayBenefits'].min()) &
                   (df['TotalPayBenefits'] < df['TotalPayBenefits'].mean())]


10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">THE END OF THE ASSIGNMENT 02</p>

# Now. it's time to relax!

![Image_Assignment](https://i.ibb.co/jZD3Mqb/relaxing.jpg)

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid"
alt="CLRSWY"></p>

___

<a href="https://clarusway.com/"><img align="center" src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" alt="CLRSWY_LOGO" title="Way to Reinvent Yourself"></a><br/>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>